// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3SI_n2zLPLil4gjh91W5Ms1HprpGdDVo',
    appId: '1:353991824699:web:2a7162b54a6117d9ba931e',
    messagingSenderId: '353991824699',
    projectId: 'final-year-project-6ebae',
    authDomain: 'final-year-project-6ebae.firebaseapp.com',
    storageBucket: 'final-year-project-6ebae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5VZ-KQtlO_KzGwdV0DFHlYfULBKIuVkI',
    appId: '1:353991824699:android:4171e19d9e6982f1ba931e',
    messagingSenderId: '353991824699',
    projectId: 'final-year-project-6ebae',
    storageBucket: 'final-year-project-6ebae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDONImHV_jh3bQU4Fs-v0oy0LxPJ6nwGI',
    appId: '1:353991824699:ios:a1675f3fdb172eeeba931e',
    messagingSenderId: '353991824699',
    projectId: 'final-year-project-6ebae',
    storageBucket: 'final-year-project-6ebae.appspot.com',
    iosBundleId: 'com.example.smartPillbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDONImHV_jh3bQU4Fs-v0oy0LxPJ6nwGI',
    appId: '1:353991824699:ios:a1675f3fdb172eeeba931e',
    messagingSenderId: '353991824699',
    projectId: 'final-year-project-6ebae',
    storageBucket: 'final-year-project-6ebae.appspot.com',
    iosBundleId: 'com.example.smartPillbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3SI_n2zLPLil4gjh91W5Ms1HprpGdDVo',
    appId: '1:353991824699:web:5471bb7f5c384001ba931e',
    messagingSenderId: '353991824699',
    projectId: 'final-year-project-6ebae',
    authDomain: 'final-year-project-6ebae.firebaseapp.com',
    storageBucket: 'final-year-project-6ebae.appspot.com',
  );
}
